// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_devSkrimp = new UnifiedLeaderboard("devSkrimp",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "devSkrimp"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI9rfxvucSEAIQAQ"
#else
            "devSkrimp"
#endif
            );

        public static UnifiedLeaderboard devSkrimp
        {
            get { return s_devSkrimp; }
        }

        private static readonly UnifiedLeaderboard s_playerLevel = new UnifiedLeaderboard("playerLevel",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "playerLevel"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI9rfxvucSEAIQAg"
#else
            "playerLevel"
#endif
            );

        public static UnifiedLeaderboard playerLevel
        {
            get { return s_playerLevel; }
        }

        private static readonly UnifiedLeaderboard s_devSkrimpPlus = new UnifiedLeaderboard("devSkrimpPlus",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "devSkrimpPlus"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI9rfxvucSEAIQAw"
#else
            "devSkrimpPlus"
#endif
            );

        public static UnifiedLeaderboard devSkrimpPlus
        {
            get { return s_devSkrimpPlus; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "devSkrimp", s_devSkrimp },
            { "playerLevel", s_playerLevel },
            { "devSkrimpPlus", s_devSkrimpPlus },
        };
    }
}
